ecommerceApp/urls.py
from django.urls import path

from .views import (
    AboutView,
    HomeView,
    ContactView,
    ProductsView,
    ProductDetailView, 
    AddToCartView,  
    CartContentView,
    CartManageView,
    EmptyCartView,
    CheckoutView,
    RegistrationView,
    CustomerLoginView,
    CustomerLogoutView,
    CustomerProfileView,
    CustomerOrderDetailView,
    AdminLoginView,
    AdminHomeView,
    AdminAllOrderView,
    AdminOrderDetailView, 
    AdminOrderStatusChangeView,
    ReSearchView,
    AdminProductsView,
    AdminAddProductView,
    PasswordForgotView,
    EmailSentView,
    PasswordResetView,
    )

app_name="ecommerceApp"
urlpatterns = [
    path("",HomeView.as_view(),name="home"),
    path("about/",AboutView.as_view(),name="about"),
    path("contact/",ContactView.as_view(),name="contact"),
    path("products/",ProductsView.as_view(),name="products"),
    path("product/<slug:slug>/",ProductDetailView.as_view(),name="product-detail"),
    path("add-to-cart/<int:id>/",AddToCartView.as_view(),name="add-to-cart"),
    path("cart-content/",CartContentView.as_view(),name="cart-content"),
    path("cart-manage/<int:cartproduct_id>/",CartManageView.as_view(),name="cart-manage"),
    path("empty-cart/",EmptyCartView.as_view(),name='empty-cart'),
    path("checkout/",CheckoutView.as_view(),name='checkout'),
    path("registration/",RegistrationView.as_view(),name='customer-registration'),
    path("customer-login/",CustomerLoginView.as_view(),name='customer-login'),
    path("customer-logout/",CustomerLogoutView.as_view(),name='customer-logout'),
    path("customer-profile/",CustomerProfileView.as_view(),name='customer-profile'),
    path("customer-order-detail/<int:pk>/",CustomerOrderDetailView.as_view(),name='customer-order-detail'),
    path("admin-login/",AdminLoginView.as_view(),name='admin-login'),
    path("admin-home/",AdminHomeView.as_view(),name='admin-home'),
    path("admin-all-order/",AdminAllOrderView.as_view(),name='admin-all-order'),
    path("admin-order-detail/<int:pk>/",AdminOrderDetailView.as_view(),name='admin-order-detail'),
    path("admin-order/<int:pk>/change",AdminOrderStatusChangeView.as_view(),name='admin-order-change'),
    path("research/",ReSearchView.as_view(),name='search-product'),
    path("admin-products/",AdminProductsView.as_view(),name="admin-products"),
    path("admin-add-product/",AdminAddProductView.as_view(),name="admin-add-product"),
    path("password-forgot/",PasswordForgotView.as_view(),name="password-forgot"),
    path("email-sent/",EmailSentView.as_view(),name="mail-sent"),
    path("password-reset/<email>/<token>/",PasswordResetView.as_view(),name="password-reset"),


    
   

]

ecommerceSite/urls.py
from django.contrib import admin
from django.urls import path,include 

from django.conf import settings

from django.conf.urls.static import static 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ecommerceApp.urls","ecommerceApp")),
]

#Append static  and media

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #For medias

ecommerceApp/models.py
from django.db import models

from django.contrib.auth.models import User

class Admin(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=60)
    telephone = models.CharField(max_length=30)
    profile_photo = models.ImageField(upload_to="Admins")
    
    def __str__(self) :
        return self.full_name
    
class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=300,verbose_name='Nom Complet')
    telephone = models.CharField(max_length=30,verbose_name='Numéro de téléphone')
    adresse = models.CharField(max_length=300,null=True,blank=True,verbose_name='Adresse de residence')
    joined_on = models.DateTimeField(auto_now_add=True)
     
    def __str__(self):
        return self.full_name
    
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    
    def __str__(self):
        return  self.title

class Product(models.Model):
    title = models.CharField(max_length=200,verbose_name='Titre')
    slug = models.SlugField(unique=True,verbose_name='Nom Unique')
    category =  models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name='Categorie')
    image = models.ImageField(upload_to='products',verbose_name='Image')
    marked_price = models.PositiveBigIntegerField(verbose_name="Prix D'Achat")
    selling_price = models.PositiveBigIntegerField(verbose_name='Prix de Vente')
    description = models.TextField(verbose_name='Description')
    warranty = models.CharField(max_length=300, null=True,blank=True,verbose_name='Garantie')
    return_policy = models.CharField(max_length=300, null=True,blank=True,verbose_name='Politique de retour')
    view_count = models.PositiveIntegerField(default=0,verbose_name='Titre')
    
    def __str__(self):
        return self.title

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image   = models.ImageField(upload_to="products/images")
    
    def __str__(self) :
        return self.product.title
        
    
class Cart(models.Model):    
    customer= models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "Cart : "+str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate =  models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveBigIntegerField()
          
    def __str__(self):
        return "Cart : "+str(self.id)+" Product : "+str(self.product.id)+" CardProduct : "+str(self.id)
    

STATUS_CHOICES=(
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Cancelled", "Order Cancelled"),
    ("Order Completed", "Order Completed"),    
)

class Order(models.Model):    
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by =  models.CharField(max_length=200)
    shipping_adress = models.CharField(max_length=200)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(null=True,blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total =  models.PositiveIntegerField()
    order_status = models.CharField(max_length=20,choices=STATUS_CHOICES)
    created_at =  models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return ' Order : '+ str(Order.id)
    
    

templates/adminPages/admin_add_product.html
{% extends 'adminPages/admin_base.html' %}

{% block title %}
 Add Product
{% endblock %}

  {% block content %}

  <h1 class=" p-5 text-center border-b-2">Ajout d'un nouveau Produit</h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-8 mx-auto" >
        <form action="" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {{form.as_p}}
         <button type="submit" class ="btn btn-primary"> Ajouter </button>
        </form>
    </div>

  </div>

  </div>

   {% endblock %}

    

templates/adminPages/admin_all_orders.html
{% extends 'adminPages/admin_base.html' %}

{% block title %}
  Admin Home
{% endblock %}

  {% block content %}

  <div class="container">

   <div class="row">
    
    <div class="col-sm-12 col-md-8 mx-auto">
        <h2 class=" p-2 text-center border-b-2 ">Liste de toutes les commandes</h2> 
        
        <table class="table table-secondary table-hover">
              <thead>
                <tr>                                     
                  <th scope="col">ID</th>
                  <th scope="col">Auteur</th>
                  <th scope="col">Adresse de Livraison</th>
                  <th scope="col">Télephone</th>
                  <th scope="col">Sous Total</th>
                  <th scope="col">Reduction</th>
                  <th scope="col">Total</th>
                  <th scope="col">Statut de la commande</th>
                  <th scope="col">Date de création</th>
                </tr>
             
              </thead>
              <tbody>

                {% for order in  orders %}
                <tr>
            <a href="{% url 'ecommerceApp:admin-order-detail' order.pk %}">   
                  <th scope="row">{{ order.id }}</th> </a> 
                  <td>{{order.ordered_by}}</td>
                  <td>{{order.shipping_adress }}</td>
                  <td>{{order.mobile}}</td>
                  <td>{{order.subtotal}} F CFA </td>
                  <td>{{order.discount}} F CFA</td>
                  <td>{{order.total }} F CFA</td>
                  <td>{{order.order_status}}</td>
                  <td>{{order.created_at }} <span class="text-primary">({{order.created_at|timesince }} ) <span></td>                
                </tr>  
            
              {% endfor %}            
              
              </tbody>
          </table>

  </div>
  
  </div>

  {% endblock %}

        

templates/adminPages/admin_base.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Ecommerce | 
              {% block title %}

            {% endblock %}</title>
        <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/14273d579a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- Font awesome bootstrap css-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--link rel="stylesheet" href="css/style.css"-->
    
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
    
    <link href="../static/base.css" rel="stylesheet">

    <script src="js/site.js"></script>    
    

    </head>
    <body>
        <header  class="mb-5">
        <nav class="navbar  navbar-expand-md  fixed-top  "style="background-color:#00008B"">
            <!--a href="..&/index.html" class="btn bg-primary text-white position-fixed ms-2" data-bs-toggle="tooltip"
            data-bs-placement="right" title="Ne pas inclure dans l'intégration">Retour</a-->
            <div class="container-fluid py-3 ">
                    <a href="index.html" class="navbar-brand text-uppercase fw-bold"> 
                      <span class="bg-gradiant text-light p-2 rounded-3">DIGIT</span>  
                        Ecommerce</a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="navbar-collapse collapse justify-content-end" id="navbarNav">

                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:admin-home' %}">Admin-Home</a>
                            </li>

                            <li class="nav-item ">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:admin-products' %}">Products</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:admin-all-order' %}">All-Order</a>
                            </li>
                           
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:home' %}" target="_blank">Visite Site</a>
                            </li>
                              </ul>                        
            </div>
            </div>

        </nav>

    </div>
    </header>
    
    <main class="mt-5">
        {% block content %}

        {% endblock %}
    </main>
    
 <footer>
 </footer>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>
    </html>

templates/adminPages/admin_home.html
{% extends 'adminPages/admin_base.html' %}

{% block title %}
  Admin Home
{% endblock %}

  {% block content %}

  <h1 class=" p-5">Espace d'Administration du site d'Ecommerce</h1>
  <div class="container">

   <div class="row">
    
    <div class="col-sm-12 col-md-8 mx-auto">
        <h2 class=" p-2 text-center border-b-2 ">Commandes Recues</h2>
        
        <table class="table table-dark table-hover">
              <thead>
                <tr>                                     
                  <th scope="col">ID</th>
                  <th scope="col">Auteur</th>
                  <th scope="col">Adresse de Livraison</th>
                  <th scope="col">Télephone</th>
                  <th scope="col">Sous Total</th>
                  <th scope="col">Reduction</th>
                  <th scope="col">Total</th>
                  <th scope="col">Statut de la commande</th>
                  <th scope="col">Date de création</th>
                </tr>
                 </thead>
              <tbody>

                {% for order in  placed_orders %}
                <tr>

                  <th scope="row"> <a href="{% url 'ecommerceApp:admin-order-detail' order.pk %}">   
                    {{ order.id }} </a> </th>
                  <td>{{order.ordered_by}}</td>
                  <td>{{order.shipping_adress }}</td>
                  <td>{{order.mobile}}</td>
                  <td>{{order.subtotal}} F CFA </td>
                  <td>{{order.discount}} F CFA</td>
                  <td>{{order.total }} F CFA</td>
                  <td>{{order.order_status}}</td>
                  <td>{{order.created_at }} <span class="text-primary">({{order.created_at|timesince }} ) <span></td>                
                </tr>  
            
              {% endfor %}            
              
              </tbody>
          </table>


  </div>
  
  </div>

  {% endblock %}

        

templates/adminPages/admin_login.html
{% extends 'adminPages/admin_base.html' %}

{% block title %}
 Admin Login
{% endblock %}

  {% block content %}

  <h1 class=" p-5 text-center border-b-2">Connexion Admin</h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-8 mx-auto" >
        <form action="" method="POST">
           {% if errors %}
           <p>{{errors}}</p>
           {% endif %}

            {% csrf_token %}
            {{form.as_p}}
         <button type="submit" class ="btn btn-primary"> Se connecter en tant qu'Admin</button>
        </form>
    </div>

  </div>

  </div>

   {% endblock %}

    

templates/adminPages/admin_order_detail.html
{% extends 'adminPages/admin_base.html' %}

{% block title %}
  Order-{{order.id }} 
{% endblock %}

  {% block content %}

  <div class="container">

   <div class="row">
    
    <div class="col-sm-12 col-md-6 mx-auto">
        <h2 class=" p-2 text-center border-b-2 ">Commande N° {{order.id}}</h2> 
        
                                         
    <p> ID  : <span>{{order.id}}</span></p>
    <p> Auteur : <span>{{order.ordered_by}}</span></p>
    <p>Adresse de Livraison : <span>{{order.shipping_adress }}</span> </p>
    <p>Télephone : <span>{{order.mobile}}</span> </p>
    <p>Sous Total :  <span>{{order.subtotal}}</span> </p>
    <p>Reduction : <span>{{order.discount}}</span> </p>
    <p> Total  : <span>{{order.total}}</span></p>
    <p>Statut de la commande :  <span>{{order.order_status}}</span></p>
    <p> Date de création : <span>{{order.created_at}}</span> </p>
               
  </div>

  <div class="col-sm-12 col-md-6">
    <h2 class=" p-5 text-center border-b-2 ">Contenu de la commande</h2> 
    
    <table class="table table-secondary table-hover">
          <thead>
            <tr> 
                <th scope="col">N° </th>                
              <th scope="col">ID </th>
              <th scope="col">ID Cart</th>
              <th scope="col">Titre Produit</th>
              <th scope="col">Prix Unitaire</th>
              <th scope="col">Quantité</th>

              <th scope="col">Sous total</th>
              
            </tr>
         
          </thead>
          <tbody>

            {% for cartproduct in  order.cart.cartproduct_set.all %}
            <tr> 
            <td>{{forloop.counter}}</td>
              <td>{{cartproduct.id}}</td>               
              <td>{{cartproduct.cart.id}}</td>
            <td> <a href="{% url 'ecommerceApp:product-detail' cartproduct.product.slug %}">{{cartproduct.product.title  }}  </a>  </td>
              <td>{{cartproduct.rate}} F CFA</td>
              <td>{{cartproduct.quantity}} F CFA </td>
              <td>{{cartproduct.subtotal}} F CFA</td>                           
            </tr>  
                     
            {% endfor %}
           
          </tbody>
      </table>

</div>

  
  </div>

  <div class="row">
    
    <div class="col-sm-12 col-md-8 mx-auto">
        <h2 class=" p-2 text-center border-b-2 ">Modifier la Statut de la Commande</h2> 

        <form action="{% url 'ecommerceApp:admin-order-change' order.id %}" method="POST">

            {% csrf_token%}
            <select name="status">
            {% for ind, status in orders_status %}
             <option value="{{ind}}"  {% if ind == order.order_status %} selected {% endif %}>{{status}}</option>
             {% endfor %}
            </select>

            <button class="btn btn-primary" type="submit">Modifier</button>
             
        </form>
                

</div>


  {% endblock %}

        

templates/adminPages/admin_products.html
{% extends 'adminPages/admin_base.html' %}

{% block title %}
 Admin | Products
{% endblock %}

  {% block content %}

  <h1 class=" p-5">Liste complète des articles  </h1>
  <div class="container">   
   <div class="row">
    <a class="btn btn-primary"  href="{% url 'ecommerceApp:admin-add-product' %}">Ajouter un produit</a>
    <table class="table table-secondary table-hover table-striped">
        <thead>
          <tr>   
            
            <th scope="col">ID</th>
            <th scope="col">Titre</th>
            <th scope="col">Slug</th>
            <th scope="col">Categorie</th>
            <th scope="col">Image</th>
            <th scope="col">Prix de vente</th>
            <th scope="col">Garrantie</th>
            <th scope="col">Politique de retour</th>
            <th scope="col">Nombre de vues</th>
          </tr>
       
        </thead>
        <tbody>
    {% for product in products %}    
    <tr>

              <th scope="row">{{ product.id }}</th>
             <td> <a href="#">   
                {{product.title}}  </a> </td>
              <td>{{product.slug }}</td>
              <td>{{product.category.title}}</td>
              <td><img src="{{ product.image.url }}" class="card-img-top" alt="loading ..." style="height:60px;">
              </td>
              <td>{{product.selling_price}} F CFA</td>
              <td>{{product.warranty}}</td>
              <td>{{product.return_policy}}</td>
              <td>{{product.view_count }} </td>                
            </tr> 
    {% endfor %}
</tbody>
</table>
  </div>
     
  </div>

 <!-- BOOTSTRAP AND DJANGO PAGINATION-->
<nav aria-label="...">
  <ul class="pagination">
    {% if products.has_previous %}
    <li class="page-item">
      <a class="page-link"  href="?page={{ categories.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a>
    </li>
    {% else %}
      <li class="page-item disabled">
      <a class="page-link"  href="#" tabindex="1" aria-disabled="true"><i class="fa fa-angle-double-left"></i></a>
    </li>
    {% endif %}


    {% for num in categories.paginator.page_range %}
    
      {% if num == categories.number %}
      <li class="page-item active"><a class="page-link" >{{num}}</a></li>
      
      {%else %}
      <li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
      {%endif%}
    {% endfor %}
   
    {% if categories.has_next %}
    <li class="page-item">
      <a class="page-link"  href="?page={{ categories.next_page_number }}"><i class="fa fa-angle-double-right"></i></a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link"  href="#"><i class="fa fa-angle-double-right"></i></a>
    </li>
    {% endif %}
  </ul>
</nav>

   {% endblock %}
        