ecommerceApp/urls.py
from django.urls import path

from .views import (
    AboutView,
    HomeView,
    ContactView,
    ProductsView,
    ProductDetailView, 
    AddToCartView,  
    CartContentView,
    CartManageView,
    EmptyCartView,
    CheckoutView,
    RegistrationView,
    CustomerLoginView,
    CustomerLogoutView,
    CustomerProfileView,
    CustomerOrderDetailView,
    AdminLoginView,
    AdminHomeView,
    AdminAllOrderView,
    AdminOrderDetailView, 
    AdminOrderStatusChangeView,
    ReSearchView,
    AdminProductsView,
    AdminAddProductView,
    PasswordForgotView,
    EmailSentView,
    PasswordResetView,
    )

app_name="ecommerceApp"
urlpatterns = [
    path("",HomeView.as_view(),name="home"),
    path("about/",AboutView.as_view(),name="about"),
    path("contact/",ContactView.as_view(),name="contact"),
    path("products/",ProductsView.as_view(),name="products"),
    path("product/<slug:slug>/",ProductDetailView.as_view(),name="product-detail"),
    path("add-to-cart/<int:id>/",AddToCartView.as_view(),name="add-to-cart"),
    path("cart-content/",CartContentView.as_view(),name="cart-content"),
    path("cart-manage/<int:cartproduct_id>/",CartManageView.as_view(),name="cart-manage"),
    path("empty-cart/",EmptyCartView.as_view(),name='empty-cart'),
    path("checkout/",CheckoutView.as_view(),name='checkout'),
    path("registration/",RegistrationView.as_view(),name='customer-registration'),
    path("customer-login/",CustomerLoginView.as_view(),name='customer-login'),
    path("customer-logout/",CustomerLogoutView.as_view(),name='customer-logout'),
    path("customer-profile/",CustomerProfileView.as_view(),name='customer-profile'),
    path("customer-order-detail/<int:pk>/",CustomerOrderDetailView.as_view(),name='customer-order-detail'),
    path("admin-login/",AdminLoginView.as_view(),name='admin-login'),
    path("admin-home/",AdminHomeView.as_view(),name='admin-home'),
    path("admin-all-order/",AdminAllOrderView.as_view(),name='admin-all-order'),
    path("admin-order-detail/<int:pk>/",AdminOrderDetailView.as_view(),name='admin-order-detail'),
    path("admin-order/<int:pk>/change",AdminOrderStatusChangeView.as_view(),name='admin-order-change'),
    path("research/",ReSearchView.as_view(),name='search-product'),
    path("admin-products/",AdminProductsView.as_view(),name="admin-products"),
    path("admin-add-product/",AdminAddProductView.as_view(),name="admin-add-product"),
    path("password-forgot/",PasswordForgotView.as_view(),name="password-forgot"),
    path("email-sent/",EmailSentView.as_view(),name="mail-sent"),
    path("password-reset/<email>/<token>/",PasswordResetView.as_view(),name="password-reset"),


    
   

]

ecommerceSite/urls.py
from django.contrib import admin
from django.urls import path,include 

from django.conf import settings

from django.conf.urls.static import static 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ecommerceApp.urls","ecommerceApp")),
]

#Append static  and media

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #For medias

ecommerceApp/models.py
from django.db import models

from django.contrib.auth.models import User

class Admin(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=60)
    telephone = models.CharField(max_length=30)
    profile_photo = models.ImageField(upload_to="Admins")
    
    def __str__(self) :
        return self.full_name
    
class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=300,verbose_name='Nom Complet')
    telephone = models.CharField(max_length=30,verbose_name='Numéro de téléphone')
    adresse = models.CharField(max_length=300,null=True,blank=True,verbose_name='Adresse de residence')
    joined_on = models.DateTimeField(auto_now_add=True)
     
    def __str__(self):
        return self.full_name
    
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    
    def __str__(self):
        return  self.title

class Product(models.Model):
    title = models.CharField(max_length=200,verbose_name='Titre')
    slug = models.SlugField(unique=True,verbose_name='Nom Unique')
    category =  models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name='Categorie')
    image = models.ImageField(upload_to='products',verbose_name='Image')
    marked_price = models.PositiveBigIntegerField(verbose_name="Prix D'Achat")
    selling_price = models.PositiveBigIntegerField(verbose_name='Prix de Vente')
    description = models.TextField(verbose_name='Description')
    warranty = models.CharField(max_length=300, null=True,blank=True,verbose_name='Garantie')
    return_policy = models.CharField(max_length=300, null=True,blank=True,verbose_name='Politique de retour')
    view_count = models.PositiveIntegerField(default=0,verbose_name='Titre')
    
    def __str__(self):
        return self.title

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image   = models.ImageField(upload_to="products/images")
    
    def __str__(self) :
        return self.product.title
        
    
class Cart(models.Model):    
    customer= models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "Cart : "+str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate =  models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveBigIntegerField()
          
    def __str__(self):
        return "Cart : "+str(self.id)+" Product : "+str(self.product.id)+" CardProduct : "+str(self.id)
    

STATUS_CHOICES=(
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Cancelled", "Order Cancelled"),
    ("Order Completed", "Order Completed"),    
)

class Order(models.Model):    
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by =  models.CharField(max_length=200)
    shipping_adress = models.CharField(max_length=200)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(null=True,blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total =  models.PositiveIntegerField()
    order_status = models.CharField(max_length=20,choices=STATUS_CHOICES)
    created_at =  models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return ' Order : '+ str(Order.id)
    
    

templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Ecommerce | 
              {% block title %}

            {% endblock %}</title>
        <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/14273d579a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- Font awesome bootstrap css-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--link rel="stylesheet" href="css/style.css"-->
    
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
    
    
    <link href="{% static 'base.css' %}" rel="stylesheet">

    <script src="js/site.js"></script>    
    

    </head>
    <body>
        <header  class="my-5 ">
        <nav class="navbar  navbar-expand-md  navbar-light fixed-top  "style="background-color:#00008B">
            <!--a href="..&/index.html" class="btn bg-primary text-white position-fixed ms-2" data-bs-toggle="tooltip"
            data-bs-placement="right" title="Ne pas inclure dans l'intégration">Retour</a-->
            <div class="container-fluid py-3  ">
                    <a href="index.html" class="navbar-brand text-uppercase fw-bold text-warning"> 
                      <span class="bg-gradiant text-light p-2 rounded-3">DIGIT</span>  
                        Ecommerce</a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="navbar-collapse collapse justify-content-end" id="navbarNav">

                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:products' %}">Articles</a>
                            </li>
                           
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:cart-content' %}">Cart</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:customer-registration' %}">Inscription</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:about' %}">A propos </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:contact' %}">Contact</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:customer-logout' %}">Se Deconnecter</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'ecommerceApp:customer-profile' %}">Mon profile</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light fw-bolder" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                  {{request.user.username }}
                                </a>
                                <ul class="dropdown-menu bg-warning" aria-labelledby="navbarDropdown">
                                  <li><a class="dropdown-item text-light" href="{% url 'ecommerceApp:customer-profile' %}">Profile</a></li>
                                  <li><a class="dropdown-item text-light" href="{% url 'ecommerceApp:customer-logout' %}">Deconnextion</a></li>
                                  <li><hr class="dropdown-divider"></li>
                                  <li><a class="dropdown-item" href="{% url 'ecommerceApp:customer-login' %}">Connexion</a></li>
                                </ul>
                              </li>
                        </ul>
                        
            </div>
            </div>

        </nav>

    </div>
    </header>

    <div class="container position-relative " style="margin-top : 50px;">

        <div class="row">
         
         <div class="col col-md-8 mx-auto" style="margin-top : 50px;">
                <form action="{% url 'ecommerceApp:search-product' %}" method="GET">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Research by title..." aria-label="Recipient's username" aria-describedby="button-addon2" name="product_keyword" required>
                        <button class="btn btn-outline-primary" type="submit" id="button-addon2">Rechercher</button>
                      </div>
                </form>
         </div>
        </div>
    </div
    
    <main class="mt-2">
        {% block content %}

        {% endblock %}
    </main>
    
 <footer>
 </footer>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>
    </html>

templates/cart_content.html
{% extends 'base.html' %}

{% block title %}
 Cart Content
{% endblock %}

  {% block content %}

  <h1 class=" p-5 text-center border-b-2">Contenu du Panier</h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-12">
        <table class="table table-secondary table-hover">
            <thead>
                <tr>
                    
                  <th scope="col">N°</th>
                  <th scope="col">Produit</th>
                  <th scope="col">Montant Evalué</th>
                  <th scope="col">Quantité</th>
                  <th scope="col">Total</th>
                  <th scope="col">Action</th>

                </tr>
              </thead>
              <tbody>

                {% for cart_product in  cart.cartproduct_set.all %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{cart_product.product.title}}</td>
                  <td>{{cart_product.rate }} F CFA</td>
                  <td>{{cart_product.quantity}}</td>
                  <td>{{cart_product.subtotal}} F CFA </td>
                  <td> 
                    <a href="{% url 'ecommerceApp:cart-manage' cart_product.id %}?action=increase" class="btn btn-primary"><i class="fa fa-plus"></i></a>
                    <a href="{% url 'ecommerceApp:cart-manage' cart_product.id %}?action=decrease" class="btn btn-warning text-light"><i class="fa fa-minus"></i></a>
                    <a href="{% url 'ecommerceApp:cart-manage' cart_product.id %}?action=delete" class="btn btn-danger fw-bolder">x</a>
                </td>

                </tr>
               
                {% endfor %}
                <tr>
                    <th colspan='2' class='text-end'>Total  :</th>
                    <th class="fs-3 fw-bold text-primary"  colspan='3'>{{cart.total }} F CFA</th> 
                    {% if cart.cartproduct_set.all %}
                    <th class="fs-3 fw-bold text-light" colspan='2'> <a href="{% url 'ecommerceApp:empty-cart' %}" class="btn btn-dark">Vider Carte</a> </th>   
                  {% endif %}     
                  </tr>
              </tbody>
          </table>
    </div>
  </div>

  </div>

   {% endblock %}

    

templates/checkout.html
{% extends 'base.html' %}

{% block title %}
 checkout Cart
{% endblock %}

  {% block content %}

  <h1 class=" p-5 text-center border-b-2">Verification du Contenu du Panier</h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-8">
        <h2 class=" p-5 text-center border-b-2 ">Contenu du Panier</h2>

        <table class="table table-secondary table-hover">
            <thead>
                <tr>
                    
                  <th scope="col">N°</th>
                  <th scope="col">Produit</th>
                  <th scope="col">Montant Evalué</th>
                  <th scope="col">Quantité</th>
                  <th scope="col">Total</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>

                {% for cart_product in  cart.cartproduct_set.all %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{cart_product.product.title}}</td>
                  <td>{{cart_product.rate }} F CFA</td>
                  <td>{{cart_product.quantity}}</td>
                  <td>{{cart_product.subtotal}} F CFA </td>
                  <td> 
                    <a href="{% url 'ecommerceApp:cart-manage' cart_product.id %}?action=increase" class="btn btn-primary"><i class="fa fa-plus"></i></a>
                    <a href="{% url 'ecommerceApp:cart-manage' cart_product.id %}?action=decrease" class="btn btn-warning text-light"><i class="fa fa-minus"></i></a>
                    <a href="{% url 'ecommerceApp:cart-manage' cart_product.id %}?action=delete" class="btn btn-danger fw-bolder">x</a>
                </td>

                </tr>               
                {% endfor %}
                <tr>
                    <th colspan='2' class='text-end'>Total  :</th>
                    <th class="fs-3 fw-bold text-primary"  colspan='3'>{{cart.total }} F CFA</th> 
                    {% if cart.cartproduct_set.all %}
                  <th class="fs-3 fw-bold text-light" colspan='2'> <a href="{% url 'ecommerceApp:empty-cart' %}" class="btn btn-dark">Vider Carte</a> </th>   
                  {% endif %}     
                  </tr>
              </tbody>
          </table>
    </div>

    <div class="col-sm-12 col-md-4">
        <h2 class=" p-5 text-center border-b-2 ">Formulaire de Verification</h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
         <button type="submit" class ="btn btn-primary"> Placer la Commande </button>
        </form>

    </div>

  </div>

  </div>

   {% endblock %}

    

templates/customer-order-detail.html
{% extends 'base.html' %}

{% block title %}
 Order Detail
{% endblock %}

  {% block content %}

  <h1 class=" p-3 text-center border-b-2"></h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-6">
        <h2 class=" p-5 text-center border-b-2 ">Informations sur la commande </h2> <hr>
        
        <p> <span>ID  : </span>{{order.id}}</p>
        <p> <span>Auteur : </span>{{order.ordered_by}} ({{order.email}})</p>
        <p> <span>Adressse de Livraison: </span>{{order.shipping_adress }} F CFA</p>
        <p> <span>Telephone : </span>{{order.mobile}}</p>
        <p> <span>Sous total  </span>{{order.subtotal}} F CFA</p>
        <p> <span>Reduction  : </span>{{order.discount}} F CFA</p>
        <p> <span>Total : </span>{{order.total}} F CFA</p>
        <p> <span>Statut : </span>{{order.order_status}} </p>
        <p> <span>Date de Création  : </span>{{order.created_at }} ({{order.created_at | timesince }}) </p>

         
    </div>

    <div class="col-sm-12 col-md-6">
        <h2 class=" p-5 text-center border-b-2 ">Contenu de la commande</h2> 
        
        <table class="table table-secondary table-hover">
              <thead>
                <tr> 
                    <th scope="col">N° </th>                
                  <th scope="col">ID </th>
                  <th scope="col">ID Cart</th>
                  <th scope="col">Titre Produit</th>
                  <th scope="col">Prix Unitaire</th>
                  <th scope="col">Sous total</th>
                  
                </tr>
             
              </thead>
              <tbody>

                {% for cartproduct in  order.cart.cartproduct_set.all %}
                <tr> 
                <td>{{forloop.counter}}</td>
                   
                 <th scope="row"> {{ cartproduct.id }}</th>
                  <td>{{cartproduct.cart.id}}</td>
             ss     <td> <a href="{% url 'ecommerceApp:product-detail' cartproduct.product.slug %}">{{cartproduct.product.title  }}  </a>  </td>
                  <td>{{cartproduct.rate}} F CFA</td>
                  <td>{{cartproduct.quantity}} F CFA </td>
                  <td>{{cartproduct.subtotal}} F CFA</td>
                               
                </tr>  
                         
                {% endfor %}
               
              </tbody>
          </table>

  </div>

  </div>

   {% endblock %}

    

templates/customerLogin.html
{% extends 'base.html' %}

{% block title %}
 Customer Login
{% endblock %}

  {% block content %}

  <h1 class=" p-5 text-center border-b-2">Connexion</h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-8 mx-auto" >
        <form action="" method="POST">
           {% if errors  %}
          
           <!-- Alert start-->
           <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
          </svg>
          <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div style="color:red; font-size:1.5rem,font-weight:bold;font-family:Arial">
              {{errors}}
            </div>
          </div>

          <!-- Alert end -->
           {% endif %}


            {% csrf_token %}
            {{form.as_p}}
         <button type="submit" class ="btn btn-primary"> Se connecter </button>
        </form>

        <p> Vous n'avez pas encore de compte ? <a href="{% url 'ecommerceApp:customer-registration' %}
            {% if request.GET.next %}next={{ request.GET.next}}{% endif %}"> S'inscrire </a> </p>

            <p>Mot de passe oublié  ?  <a href="{% url 'ecommerceApp:password-forgot' %}"> Réinitialier</a> </p>
    </div>

  </div>

  </div>

   {% endblock %}

    

templates/customer_profile.html
{% extends 'base.html' %}

{% block title %}
 My Profile
{% endblock %}

  {% block content %}

  <h1 class=" p-3 text-center border-b-2"></h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-4">
        <h2 class=" p-5 text-center border-b-2 ">Detail Informations</h2> <hr>
        
        <p> <span>Username : </span>{{customer.user.username}}</p>
        <p> <span>Email : </span>{{customer.user.email}}</p>
        <p> <span>Nom complet : </span>{{customer.full_name}}</p>
        <p> <span>Adresse: </span>{{customer.adresse}}</p>
        <p> <span>Telephone : </span>{{customer.telephone}}</p>
        <p> <span>Date d'inscription : </span>{{customer.joined_on | timesince}}</p>
                
    </div>

    <div class="col-sm-12 col-md-8">
        <h2 class=" p-5 text-center border-b-2 ">Mes commandes effectuées</h2> 
        
        <table class="table table-secondary table-hover">
              <thead>
                <tr> 
                                    
                  <th scope="col">ID</th>
                  <th scope="col">Auteur</th>
                  <th scope="col">Adresse de Livraison</th>
                  <th scope="col">Télephone</th>
                  <th scope="col">Sous Total</th>
                  <th scope="col">Reduction</th>
                  <th scope="col">Total</th>
                  <th scope="col">Statut de la commande</th>
                  <th scope="col">Date de création</th>
                </tr>
             
              </thead>
              <tbody>

                {% for order in  orders %}
                <a href="{% url 'ecommerceApp:customer-order-detail' order.pk %}"> 
                <tr>
                  <th scope="row">{{ order.id }}</th>
                  <td>{{order.ordered_by}}</td>
                  <td>{{order.shipping_adress }} F CFA</td>
                  <td>{{order.mobile}}</td>
                  <td>{{order.subtotal}} F CFA </td>
                  <td>{{order.discount}} F CFA</td>
                  <td>{{order.total }} F CFA</td>
                  <td>{{order.order_status}}</td>
                  <td>{{order.created_at }} F CFA </td>
                
                </tr>  
              </a>             
                {% endfor %}
                <tr>
                    <th colspan='2' class='text-end'>Total  :</th>
                    <th class="fs-3 fw-bold text-primary"  colspan='3'>{{cart.total }} F CFA</th> 
                    {% if cart.cartproduct_set.all %}
                  <th class="fs-3 fw-bold text-light" colspan='2'> <a href="{% url 'ecommerceApp:empty-cart' %}" class="btn btn-dark">Vider Carte</a> </th>   
                  {% endif %}     
                  </tr>
              </tbody>
          </table>

  </div>

  </div>

   {% endblock %}

    

templates/produits.html
{% extends 'base.html' %}

{% block title %}
 Articles
{% endblock %}

  {% block content %}

  <h1 class=" p-5">Visualisez nos produits vendus par catégorie </h1>
  <div class="container">
 
    {% for categorie in categories %}
    {% if  categorie.product_set.all %}
    <h1 class="fw-bold fs-4 mt-3">{{categorie.title}}</h1> <hr>
   
   <div class="row">
    
    {% for produit in categorie.product_set.all %}
    
    <div class="col col-md-3">
      <div class="card shadow border-2 border-primary img-fluid mb-2" style="width: 18rem; height:400px; object-fit:cover;">
        <img src="{{ produit.image.url }}" class="card-img-top" alt="loading ..." style="height:55%;">
        <div class="card-body">
          <h5 class="card-title fw-bolder">{{produit.title}}</h5>
          <p class="card-text text-center mt-3"> <strike>Price : {{produit.marked_price}} F CFA  </strike>| <span class="fw-bolder"> Ps : {{produit.selling_price}} F CFA <span></p>
          <a href="{%  url 'ecommerceApp:add-to-cart' produit.id %}" class="btn btn-primary fs-6">Add to Cart</a>
          <a href="{%  url 'ecommerceApp:product-detail' produit.slug %}" class="btn btn-dark fs-6">Details</a>
        </div>
      </div>

    </div>

    {% endfor %}
  </div>
  {% endif %}
  {% endfor %}
    
  </div>

 <!-- BOOTSTRAP AND DJANGO PAGINATION-->
<nav aria-label="...">
  <ul class="pagination">
    {% if products.has_previous %}
    <li class="page-item">
      <a class="page-link"  href="?page={{ categories.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a>
    </li>
    {% else %}
      <li class="page-item disabled">
      <a class="page-link"  href="#" tabindex="1" aria-disabled="true"><i class="fa fa-angle-double-left"></i></a>
    </li>
    {% endif %}


    {% for num in categories.paginator.page_range %}
    
      {% if num == categories.number %}
      <li class="page-item active"><a class="page-link" >{{num}}</a></li>
      
      {%else %}
      <li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
      {%endif%}
    {% endfor %}
   
    {% if categories.has_next %}
    <li class="page-item">
      <a class="page-link"  href="?page={{ categories.next_page_number }}"><i class="fa fa-angle-double-right"></i></a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link"  href="#"><i class="fa fa-angle-double-right"></i></a>
    </li>
    {% endif %}
  </ul>
</nav>

   {% endblock %}
        